---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ngigo-web-ingress
  labels:
    name: ngigo-web-ingress
spec:
  rules:
  - host: ngigo.com
    http:
      paths:
      - backend:
          serviceName: ngigo-web
          servicePort: 31000