---
apiVersion: v1 
kind: Service 
metadata:
  name: ngigo-web-service
spec:
  type: NodePort
  ports:
    - name: http 
      port: 8000
      targetPort: 8000
      nodePort: 8000
  selector:
    app: ngigo-web
