name: ngigo-web build and deploy to k8s
run-name: Ngigo web api deployment
on:
  push:
    branches:
      - main
      - dev
jobs:
  fetch-latest-and-build-image:
    runs-on: 
      - self-hosted
      - amsterdam
    steps:
      - 
        name: checkout and fetch
        uses: actions/checkout@v3
      
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      -
        name: login to docker
        uses: docker/login-action@v2
        with:
          registry: registry.sinabehmanesh.com
          username: "actions"
          password: "act123"
          # username: ${{ secrets.REGISTRY_USERNAME }}
          # password: ${{ secrets.REGISTRY_PASSWORD }}
      
      -
        name: build and push image to Repository
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "registry.sinabehmanesh.com/ngigo-web:latest"

  pull-image-and-deploy-to-kubernetes-cluster:
    runs-on:
      - self-hosted
      - local
    needs: fetch-latest-and-build-image
    steps:
      -
        name: fetch kubernetes manifests
        uses: actions/checkout@v3
      - 
        name: deploy to cluster
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        run: kubectl apply -f ./kubernetes

  test-deployment-availability:
    runs-on:
      - self-hosted
      - local
    needs:
      - pull-image-and-deploy-to-kubernetes-cluster
    steps:
      -
        name: curl endporint
        run: curl http://localhost31000/login
