name: ngigo-web build and deploy to k8s
run-name: ${{ github.actor }} is starting.
on:
  push:
    branches:
      - main
      - dev
jobs:
  fetch-latest-and-build-image:
  runs-on: amsterdam
  steps:
    - 
      name: checkout and fetch
      uses: actions/checkout@v3
    
    -
      name: login to docker
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.DOCKERREGISTRY}}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    -
      name: build and push image to Repository
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/ngigo-web:latest